/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'ciphertext' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface Profile { 'displayName' : string, 'encryptionKey' : string }
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteConversation' : ActorMethod<[Principal], undefined>,
  'deleteMessage' : ActorMethod<[Principal, Time], undefined>,
  'getCallerProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerProfile' : ActorMethod<[string, string], undefined>,
  'searchUsers' : ActorMethod<[string], Array<[Principal, string]>>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'startConversation' : ActorMethod<[Principal], undefined>,
  'updateDisplayName' : ActorMethod<[string], undefined>,
  'updateEncryptionKey' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];