/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Profile = IDL.Record({
  'displayName' : IDL.Text,
  'encryptionKey' : IDL.Text,
});
export const Message = IDL.Record({
  'ciphertext' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteConversation' : IDL.Func([IDL.Principal], [], []),
  'deleteMessage' : IDL.Func([IDL.Principal, Time], [], []),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'searchUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'startConversation' : IDL.Func([IDL.Principal], [], []),
  'updateDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateEncryptionKey' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Profile = IDL.Record({
    'displayName' : IDL.Text,
    'encryptionKey' : IDL.Text,
  });
  const Message = IDL.Record({
    'ciphertext' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteConversation' : IDL.Func([IDL.Principal], [], []),
    'deleteMessage' : IDL.Func([IDL.Principal, Time], [], []),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'searchUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'startConversation' : IDL.Func([IDL.Principal], [], []),
    'updateDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateEncryptionKey' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };